config/routes.rb
Rails.application.routes.draw do
  scope "/:locale" do
    resources :genres
    resources :languages
    resources :periods
    resources :composers
    resources :account
    resources :admin_users
    resources :messages
    resources :links, :except => [:show, :index]

    resources :evensongs
#    resources :evensongs do
#      collection do
#        post 'sorted'
#      end
#    end

    resources :notes do
      collection do
        get 'voices'
      end
#      collection do
#        post 'sorted'
#      end
    end

    resources :uploads do
      collection do
        get 'link'
      end
      member do
        get 'refresh'
      end
    end

    resources :dropbox do
      collection do
        get 'authorize'
      end
    end


    match 'search/:type' => 'search#index', :as => :typedsearch, via: [:get, :post]

    match 'search' => 'search#search', :as => :search, via: [:get, :post]

    match 'typeahead' => 'search#typeahead', :as => :searchahead, via: [:get]

    devise_for :users

  end

  get '/:locale' => 'notes#index'
  root :to => 'notes#index'

end

app/models/note.rb
class Note < ActiveRecord::Base
  include AbstractNote
  include Searchable

  belongs_to :genre, counter_cache: true
  belongs_to :language, counter_cache: true
  belongs_to :period, counter_cache: true
  belongs_to :composer, counter_cache: true

  before_destroy :remove_links
  before_destroy :remove_uploads

  has_many :links
  has_many :uploads

  delegate :name, :to => :genre, :prefix => true, :allow_nil => true
  delegate :name, :to => :composer, :prefix => true, :allow_nil => true
  delegate :name, :to => :period, :prefix => true, :allow_nil => true
  delegate :name, :to => :language, :prefix => true, :allow_nil => true

  before_validation(:on => :create) { set_next_item }

  validates_presence_of :item, :title, :originals

  scope :ordered, -> { order(:title) }
  scope :preloaded, -> { includes :composer, :genre, :period, :language, :uploads }

  def get_typeahead
    [title, voice, soloists, instrument, comment, composer_name, genre_name, period_name, language_name].flatten
  end

  def self.voices
    Note.select('distinct voice').map(&:voice).sort
  end

  def as_indexed_json(options={})
    as_json(
        only: [:comment, :item, :soloists, :title, :voice, :id, :instrument],
        include: {
            genre: {only: :name},
            language: {only: :name},
            period: {only: :name},
            composer: {only: :name}
        }
    )
  end

  begin
    def self.excel
      NoteSheet.new([HeaderColumn.new(I18n.t('table.title.sysid'), 8),
                     HeaderColumn.new(I18n.t('table.title.item'), 8),
                     HeaderColumn.new(I18n.t('table.title.title'), 50),
                     HeaderColumn.new(I18n.t('table.title.composer'), 35),
                     HeaderColumn.new(I18n.t('table.title.genre'), 35),
                     HeaderColumn.new(I18n.t('table.title.period'), 35),
                     HeaderColumn.new(I18n.t('table.title.language'), 35),
                     HeaderColumn.new(I18n.t('table.title.instrument'), 35),
                     HeaderColumn.new(I18n.t('table.title.originals'), 8),
                     HeaderColumn.new(I18n.t('table.title.copies'), 8),
                     HeaderColumn.new(I18n.t('table.title.instrumental'), 8),
                     HeaderColumn.new(I18n.t('table.title.voices'), 15),
                     HeaderColumn.new(I18n.t('table.title.soloists'), 35),
                     HeaderColumn.new(I18n.t('table.title.comment'), 50)],
                    Note.ordered.preloaded,
                    I18n.t('page.notes.title'),
                    lambda { |row, item|
                      row.push item.id
                      row.push item.item
                      row.push item.title
                      row.push item.composer_name
                      row.push item.genre_name
                      row.push item.period_name
                      row.push item.language_name
                      row.push item.instrument
                      row.push item.originals
                      row.push item.copies
                      row.push item.instrumental
                      row.push item.voice
                      row.push item.soloists
                      row.push item.comment
                    })
    end
  end

  private

  def set_next_item
    self.item = Note.maximum(:item) + 1
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  filter_access_to :all

  before_action :set_note, only: [:show, :edit, :update, :destroy]

  def index
    set_accept_header

    session.delete :lastsearch

    @notes = Note.ordered.preloaded

    respond_to do |format|
      format.html { redirect_to typedsearch_url( :type => 'note' ) }
      format.xls { index_excel }
    end
  end

  def show
    @show = {
        :note => @note
    }
=begin
    search_notes = []

    joins = []

    if session[:lastsort].has_key? :note
      order_clause = session[:lastsort][:note].map do |sort|
        col = sort['column']

        if col == 'composer'
          col = "composers.name"
          joins << :composer
        end

        if col == 'genre'
          col = "genres.name"
          joins << :genre
        end

        if col == 'period'
          col = "periods.name"
          joins << :period
        end

        if col == 'language'
          col = "languages.name"
          joins << :language
        end

        "LOWER(#{col}) #{sort['direction']}"
      end.join ","

      unless order_clause.include?("title")
        order_clause += ",LOWER(notes.title) ASC"
      end
    else
      order_clause = "LOWER(title) ASC"
    end

    query = Note.order(order_clause)

    if joins.size > 0
      joins.each do |joined|
        query = query.joins(joined)
      end
    end

    if session.has_key? :lastsearch
      search_notes = query.search(session[:lastsearch]).preloaded
    else
      search_notes = query.preloaded
    end

    if search_notes.size > 0
      current_index = search_notes.index(@note)

      if current_index > 0
        @show[:first] = search_notes.first
        @show[:previous]= search_notes.at(current_index - 1)
      end

      if current_index < (search_notes.size - 1)
        @show[:last] = search_notes.last
        @show[:next] = search_notes.at(current_index + 1)
      end
    end
=end
  end

  def new
    @note = Note.new
  end

  def edit
  end

  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to notes_url, notice: t('create.note.ok') }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to notes_url, notice: t('update.note.ok') }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: t('delete.note.ok') }
      format.json { head :no_content }
    end
  end

=begin
  def sorted
    session[:lastsort][:note] = params[:sorting].values

    render :json => 'ok'
  end
=end

  def voices
    render :json => Note.voices.select { |v| v.upcase.start_with? params[:search] }
  end

  private

  begin
    def index_excel
      excel = Note.excel

      send_file(excel.get_spreadsheet,
                :type => 'application/vnd.ms-excel',
                :disposition => 'attachment',
                :filename => excel.get_filename)
    end
  end

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:item, :title, :soloists, :voice, :instrument, :originals, :copies, :instrumental, :comment, :composer_id, :genre_id, :period_id, :language_id)
  end
end

app/views/notes/_actions.html.haml
.well
  - if permitted_to? :new, :notes
    = link_to t('link.new'), new_note_path, :class => 'btn btn-primary btn-xs'
  - if permitted_to? :index, :notes
    = link_to link_with_icon('download', t('link.download')), notes_path(:format => :xls), :class => 'btn btn-default btn-xs'

app/views/notes/_form.html.haml
.container
  .row
    .col-md-6
      %h2= title

      = form_for item do |f|
        = render 'shared/validation_messages', :errors => item.errors

        .form-group
          = f.label :item, :class => 'control-label'
          = f.text_field :item, :class => 'form-control', :placeholder => t('placeholder.note.item')

        .form-group
          = f.label :title, :class => 'control-label'
          = f.text_field :title, :class => 'form-control'

        .form-group
          = f.label :soloists, :class => 'control-label'
          = f.text_field :soloists, :class => 'form-control'

        .form-group
          = f.label :voice, :class => 'control-label'
          = f.text_field :voice, :data => { :'typeahead-link' => voices_notes_url( :format => :json ) }, :class => 'form-control'

        .form-group
          = f.label :instrument, :class => 'control-label'
          = f.text_field :instrument, :class => 'form-control'

        .form-group
          = f.label :originals, :class => 'control-label'
          = f.text_field :originals, :class => 'form-control'

        .form-group
          = f.label :copies, :class => 'control-label'
          = f.text_field :copies, :class => 'form-control'

        .form-group
          = f.label :instrumental, :class => 'control-label'
          = f.text_field :instrumental, :class => 'form-control'

        .form-group
          = f.label :comment, :class => 'control-label'
          = f.text_area :comment, :class => 'form-control'

        .form-group
          = f.label :composer, :class => 'control-label'
          = f.collection_select :composer_id, Composer.ordered, :id, :name, :prompt => true, :class => 'form-control'

        .form-group
          = f.label :genre, :class => 'control-label'
          = f.collection_select :genre_id, Genre.ordered, :id, :name, :prompt => true, :class => 'form-control'

        .form-group
          = f.label :period, :class => 'control-label'
          = f.collection_select :period_id, Period.ordered, :id, :name, :prompt => true, :class => 'form-control'

        .form-group
          = f.label :language, :class => 'control-label'
          = f.collection_select :language_id, Language.ordered, :id, :name, :prompt => true, :class => 'form-control'

        .well
          = f.submit t('button.update'), :class => 'btn btn-primary btn-xs'
          = link_to t('button.cancel'), notes_path, :class => 'btn btn-default btn-xs'

app/views/notes/_table.html.haml
%table#notes.table.table-bordered.table-condensed.table-striped.sortable
  %thead
    %tr
      %th= t('table.title.item')
      %th= t('table.title.title')
      %th= t('table.title.composer')
      %th= t('table.title.genre')
      %th= t('table.title.period')
      %th= t('table.title.language')
      %th= t('table.title.instrument')
      %th{ :class => '{sorter: false}' }= t('table.title.upload')
  %tbody
    - items = rows.group_by(&:id)
    - ids.each do |id|
      - item = items[id].first
      %tr
        %td= item.item
        %td
          - if permitted_to? :show, item
            = link_to item.title, note_path(item)
          - else
            = item.title
        %td= search_link 'composer', item.composer_name
        %td= search_link 'genre', item.genre_name
        %td= search_link 'period', item.period_name
        %td= search_link 'language', item.language_name
        %td= search_link 'instrument', item.instrument
        %td
          - item.uploads.each do |u|
            = short_media_link u, note_path(item)

app/views/notes/edit.html.haml
- title(@note.title, false)

= render 'form', :item => @note, :title => t('page.note.title')

app/views/notes/index.html.haml
- title t('page.notes.title')

= render 'actions'

= render 'table', :ids => @notes.map(&:id), :rows => @notes

= render 'actions'

app/views/notes/new.html.haml
- title(t('page.note.title'), false)

= render 'form', :item => @note, :title => t('page.note.title')

app/views/notes/show.html.haml
- title @show[:note].title

%table.table.table-striped.table-condensed
  %thead
    %tr
      %th= t('table.title.key')
      %th= t('table.title.value')
  %tbody
    %tr
      %td= t('table.title.item')
      %td= @show[:note].item
    %tr
      %td= t('table.title.title')
      %td= @show[:note].title
    %tr
      %td= t('table.title.composer')
      %td= search_link 'composer', @show[:note].composer_name
    %tr
      %td= t('table.title.genre')
      %td= search_link 'genre', @show[:note].genre_name
    %tr
      %td= t('table.title.period')
      %td= search_link 'period', @show[:note].period_name
    %tr
      %td= t('table.title.language')
      %td= search_link 'langauge', @show[:note].language_name
    %tr
      %td= t('table.title.soloists')
      %td= search_link 'search', @show[:note].soloists
    %tr
      %td= t('table.title.instrument')
      %td= search_link 'instrument', @show[:note].instrument
    %tr
      %td= t('table.title.originals')
      %td= @show[:note].originals
    %tr
      %td= t('table.title.copies')
      %td= @show[:note].copies
    %tr
      %td= t('table.title.instrumental')
      %td= @show[:note].instrumental
    %tr
      %td= t('table.title.voices')
      %td= search_link 'voice', @show[:note].voice
    %tr
      %td= t('table.title.comment')
      %td= @show[:note].comment
    %tr
      %td= t('table.title.links')
      %td
        - if permitted_to?(:show, :links)
          - if @show[:note].links
            = render :partial => 'shared/show_links_list', :locals => { :links => @show[:note].links }
    %tr
      %td= t('table.title.upload')
      %td
        - if @show[:note].uploads
          = render :partial => 'shared/show_uploads_list', :locals => { :uploads => @show[:note].uploads }

.well
  = link_to t('link.back'), :back, :class => 'btn btn-default btn-xs'
  -# if @show[:first]
    = link_to t('show.button.first'), note_path(@show[:first]), :class => 'btn btn-default btn-xs'
  -# if @show[:previous]
    = link_to t('show.button.previous'), note_path(@show[:previous]), :class => 'btn btn-default btn-xs'
  -# if @show[:next]
    = link_to t('show.button.next'), note_path(@show[:next]), :class => 'btn btn-default btn-xs'
  -# if @show[:last]
    = link_to t('show.button.last'), note_path(@show[:last]), :class => 'btn btn-default btn-xs'
  -# if session.has_key? :lastsearch
    = link_to t('model.note.list.title'), search_path(:search => session[:lastsearch]), :class => 'btn btn-default btn-xs'
  -# else
    = link_to t('model.note.list.title'), notes_path, :class => 'btn btn-default btn-xs'
  - if permitted_to?(:edit, @show[:note])
    = link_to t('button.edit'), edit_note_path(@show[:note]), :class => 'btn btn-default btn-xs'
  - if permitted_to?(:new, :links)
    = link_to t('button.link'), new_link_path(:note => @show[:note].id), :class => 'btn btn-default btn-xs'
  - if permitted_to?(:new, :uploads)
    = link_to t('button.upload'), new_upload_path(:note => @show[:note].id), :class => 'btn btn-default btn-xs'
  - if permitted_to?(:link, :uploads)
    = link_to t('button.attach'), link_uploads_path(:note => @show[:note].id), :class => 'btn btn-default btn-xs', :rel => 'popover', :data => { :container => 'body', :toggle => 'popover', :title => t('link.file.title'), :content => t('refresh.warning'), :trigger => 'hover', :placement => 'right' }
  - if permitted_to?(:destroy, @show[:note])
    = link_to t('link.delete'), @show[:note], method: :delete, data: { confirm: t('link.destroy.confirm') }, :class => 'btn btn-danger btn-xs'