config/routes.rb
Rails.application.routes.draw do
  scope "/:locale" do
    resources :genres
    resources :languages
    resources :periods
    resources :composers
    resources :account
    resources :admin_users
    resources :messages
    resources :links, :except => [:show, :index]

    resources :evensongs
#    resources :evensongs do
#      collection do
#        post 'sorted'
#      end
#    end

    resources :notes do
      collection do
        get 'voices'
      end
#      collection do
#        post 'sorted'
#      end
    end

    resources :uploads do
      collection do
        get 'link'
      end
      member do
        get 'refresh'
      end
    end

    resources :dropbox do
      collection do
        get 'authorize'
      end
    end


    match 'search/:type' => 'search#index', :as => :typedsearch, via: [:get, :post]

    match 'search' => 'search#search', :as => :search, via: [:get, :post]

    match 'typeahead' => 'search#typeahead', :as => :searchahead, via: [:get]

    devise_for :users

  end

  get '/:locale' => 'notes#index'
  root :to => 'notes#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable,
         :recoverable, :trackable, :timeoutable

  has_many :user_role_relations
  has_many :roles, :through => :user_role_relations

  scope :ordered, -> { order(:name) }
  scope :preloaded, -> { includes :roles }

  validates_presence_of :username, :name, :email, :roles

  def role_symbols
    roles.map do |role|
      role.name.underscore.to_sym
    end
  end

  def display_name
    name.blank? ? username : name
  end
end

app/controllers/users_controller.rb
# coding: UTF-8

class UsersController < ApplicationController
  filter_access_to :all

  before_filter :get_user, :only => [:edit, :show, :update, :destroy]

  layout "wide"

  def index
    @users = User.preloaded
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      flash[:notice] = t('model.user.create.ok')
      redirect_to :action => "index"
    else
      render :new
    end
  end

  def edit
  end

  def show
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:notice] = t('model.user.update.ok')
      redirect_to :action => "index"
    else
      render :edit
    end
  end

  def destroy
    if @user.username == current_user.username
      redirect_to user_url(@user), alert: t('model.user.delete.self')
    else
      @user.destroy

      redirect_to users_url, notice: t('model.user.delete.ok')
    end
  end

  private

  def get_user
    @user = User.find(params[:id])
  end

end

app/views/users/_form.html.haml
= simple_form_for user, :html => {:class => 'form-horizontal'} do |f|
  %fieldset
    %legend= t('user.form.legend')

    - if full
      = f.input :username
    = f.input :name
    = f.input :email
    - if full
      = f.input :password
      = f.input :password_confirmation

    = f.association :roles, as: :check_boxes

    %div.form-actions
      = f.button :submit, :class => 'btn-primary'

app/views/users/edit.html.haml
- title @user.username
= render :partial => 'form', :locals => { :user => @user, :full => false }

app/views/users/index.html.haml
- title t('user.list.title')
%h1= t('user.list.title')

- if permitted_to? :new, :users
  %div.well
    = link_to t('list.button.new'), new_user_path, :class => 'btn btn-primary'

%table.table.table-striped.table-condensed
  %thead
    %tr
      %th
        Username
      %th
        Name
      %th
        E-mail
      %th
        Updated
      %th
        Login Count
      %th
        Failed Login Count
      %th
        Last Request
      %th
        Current Login
      %th
        Current Login IP
      %th
        Roles
  %tbody
    - for user in @users
      %tr
        %td= link_to user.username, user_path(user)
        %td= user.name
        %td= user.email
        %td= user.updated_at
        %td= user.login_count
        %td= user.failed_login_count
        %td= user.last_request_at
        %td= user.current_login_at
        %td= user.current_login_ip
        %td
          %ul.unstyled
            - user.roles.each do |role|
              %li= role.name

app/views/users/new.html.haml
- title t('user.list.title')
= render :partial => 'form', :locals => { :user => @user, :full => true }

app/views/users/show.html.haml
- title @user.username
%h2= @user.username

%br

%table.table.table-striped.table-condensed
  %tr
    %td
      Email
    %td= @user.email
  %tr
    %td
      Name
    %td= @user.name
  %tr
    %td
      Created
    %td= @user.created_at
  %tr
    %td
      Updated
    %td= @user.updated_at
  %tr
    %td
      Login Count
    %td= @user.login_count
  %tr
    %td
      Failed Login Count
    %td= @user.failed_login_count
  %tr
    %td
      Last Request
    %td= @user.last_request_at
  %tr
    %td
      Current Login
    %td= @user.current_login_at
  %tr
    %td
      Last Login
    %td= @user.last_login_at
  %tr
    %td
      Current Login IP
    %td= @user.current_login_ip
  %tr
    %td
      Last Login IP
    %td= @user.last_login_ip
  %tr
    %td
      Roles
    %td
      %ul.unstyled
        - @user.roles.each do |role|
          %li= role.name

%br

%div.form-actions
  = link_to t('back'), :back, :class => 'btn'
  - if permitted_to? :edit, @user
    = link_to 'Endre', edit_user_path(@user), :class => 'btn'
  - if permitted_to? :index, :users
    = link_to 'Back to users', users_path, :class => 'btn'
  - if permitted_to?(:destroy, @user) && current_user.username != @user.username
    = link_to t('show.button.delete'), user_path(@user), :method => 'delete', :confirm => t('show.delete.confirm'), :class => 'btn btn-danger'