config/routes.rb
Rails.application.routes.draw do
  scope "/:locale" do
    resources :genres
    resources :languages
    resources :periods
    resources :composers
    resources :account
    resources :admin_users
    resources :messages
    resources :links, :except => [:show, :index]

    resources :evensongs
#    resources :evensongs do
#      collection do
#        post 'sorted'
#      end
#    end

    resources :notes do
      collection do
        get 'voices'
      end
#      collection do
#        post 'sorted'
#      end
    end

    resources :uploads do
      collection do
        get 'link'
      end
      member do
        get 'refresh'
      end
    end

    resources :dropbox do
      collection do
        get 'authorize'
      end
    end


    match 'search/:type' => 'search#index', :as => :typedsearch, via: [:get, :post]

    match 'search' => 'search#search', :as => :search, via: [:get, :post]

    match 'typeahead' => 'search#typeahead', :as => :searchahead, via: [:get]

    devise_for :users

  end

  get '/:locale' => 'notes#index'
  root :to => 'notes#index'

end

app/views/shared/_facet.html.haml
- aggregations.sort.each do |name, aggregation|
  - buckets = (aggregation.has_key?('counts') ? aggregation['counts']['buckets'] : aggregation['buckets'])
  - if buckets.size > 1
    %h3= t("page.title.#{name}s")
    .list-group
      - buckets.each do |bucket|
        - unless bucket['key'].blank?
          %a.list-group-item{:href => url_for(request.GET.merge(name => bucket['key']))}
            %span.badge= bucket['doc_count']
            = bucket['key']

app/views/shared/_footer.html.haml
%footer#footer
  = render '/shared/google_analytics'
  .container
    = link_to 'OHCS', "http://ochs.no"
    |
    = link_to t('footer.github'), 'https://github.com/chrissearle/notearkiv'

app/views/shared/_head.html.haml
%head
  %title= h(yield(:title) || "OCHS")
  /[if lt IE 9]
    %script{ :src => "http://html5shim.googlecode.com/svn/trunk/html5.js", :type => "text/javascript" }
  = stylesheet_link_tag "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
  %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

app/views/shared/_nameform.html.haml
%h1= title

.container
  .row
    .col-md-3

    .col-md-6
      = form_for(item) do |f|
        = render 'shared/validation_messages', :errors => item.errors

        .form-group
          = f.label :name, :class => 'control-label'
          = f.text_field :name, :class => 'form-control'

        .well
          = f.submit :class => 'btn btn-primary btn-xs'
          = link_to t('link.back'), polymorphic_url(item.class), :class => 'btn btn-default btn-xs'

    .col-md-3

app/views/shared/_navbar.html.haml
%div.navbar.navbar-fixed-top.navbar-inverse
  %div.navbar-inner
    %div.container
      %a.btn.btn-navbar{ :'data-toggle' => "collapse", :'data-target' => ".nav-collapse" }
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.brand{ :href => "#" } OCHS

      %div.nav-collapse
        = render :partial => 'shared/navbar_left_menu'
        = render :partial => 'shared/navbar_search_form'
        = render :partial => 'shared/navbar_right_menu'

app/views/shared/_navbar_left_menu.html.haml
%ul.nav
  - if current_user
    - if permitted_to? :index, :notes
      %li= link_to t('model.note.list.title'), notes_path
    - if permitted_to? :index, :evensongs
      %li= link_to t('model.evensong.list.title'), evensongs_path

app/views/shared/_navbar_right_menu.html.haml
%ul.nav.pull-right
  - if current_user
    %li.divider-vertical
    = render :partial => 'shared/navbar_right_menu_categories'
    %li.divider-vertical
    = render :partial => 'shared/navbar_right_menu_account'
    %li.divider-vertical
    = render :partial => 'shared/navbar_right_menu_language'
    %li.divider-vertical
    %li= link_to t('menu.logout'), logout_path

app/views/shared/_navbar_right_menu_account.html.haml
%li.dropdown
  %a.dropdown-toggle{ :href => "#", :'data-toggle' => "dropdown" }
    = link_with_icon( 'icon-user', t('menu.dropdown.account'), true)
    %b.caret
  %ul.dropdown-menu
    - if permitted_to? :index, :account
      %li= link_to t('account.list.title'), url_for(:controller => 'account', :action => 'index')
    - if permitted_to? :index, :messages
      %li= link_to t('model.message.list.title'), messages_path
    - if permitted_to? :index, :users
      %li= link_to t('account.users.list.title'), users_path
    - if permitted_to? :index, :dropbox
      %li= link_to t('account.dropbox.list.title'), dropbox_index_path

app/views/shared/_navbar_search_form.html.haml
- if current_user
  = form_tag(search_path, :method => 'get', :class => 'navbar-search pull-left') do
    = text_field_tag "search", params[:search], :class => 'search-query', :id => 'mainsearch', :placeholder => 'Search', :data => { :typeahead_link => searchahead_url }

app/views/shared/_navigation_links_right.html.haml
%ul.nav.navbar-nav.navbar-right
  - if current_user
    %li.dropdown
      %a.dropdown-toggle{ :href => '#', :'data-toggle' => 'dropdown' }
        = link_with_icon('tags', t('menu.dropdown.categories'))
        %b.caret
      %ul.dropdown-menu
        - if permitted_to? :index, :composers
          %li= link_to t('menu.composer.title'), composers_path
        - if permitted_to? :index, :genres
          %li= link_to t('menu.genre.title'), genres_path
        - if permitted_to? :index, :periods
          %li= link_to t('menu.period.title'), periods_path
        - if permitted_to? :index, :languages
          %li= link_to t('menu.language.title'), languages_path
    %li.divider-vertical
    %li.dropdown
      %a.dropdown-toggle{ :href => "#", :'data-toggle' => "dropdown" }
        = link_with_icon( 'user', t('menu.dropdown.account'))
        %b.caret
      %ul.dropdown-menu
        - if permitted_to? :index, :messages
          %li= link_to t('menu.message.title'), messages_path
        - if permitted_to? :index, :account
          %li= link_to t('menu.account.title'), url_for(:controller => 'account', :action => 'index')
        - if permitted_to? :index, :admin_users
          %li= link_to t('menu.users.title'), admin_users_path
        - if permitted_to? :index, :dropbox
          %li= link_to t('menu.dropbox.title'), dropbox_index_path
    %li.divider-vertical
    %li.dropdown
      %a.dropdown-toggle{ :href => '#', :'data-toggle' => 'dropdown' }
        = link_with_icon( 'user', t('menu.dropdown.language'))
        %b.caret
      %ul.dropdown-menu
        %li= link_to t('menu.language.norwegian'), url_for(request.GET.merge(:locale => 'nb'))
        %li= link_to t('menu.language.english'), url_for(request.GET.merge(:locale => 'en'))
    %li= link_to t('menu.logout'), destroy_user_session_path, :method => :delete
  - else
    %li= link_to t('menu.login'), new_user_session_path

app/views/shared/_navigation_search.html.haml
- if current_user
  = form_tag(typedsearch_path(:type => 'all'), :method => 'get', :class => 'navbar-form navbar-left', :role => 'search') do
    .form-group
      = text_field_tag 'search', params[:search], :class => 'form-control', :id => 'mainsearch', :placeholder => t('link.search'), :data => { :typeahead_link => searchahead_url }
    %button.btn.btn-default{ :type => 'submit' }= t('link.search')

app/views/shared/_right_logged_in.html.haml
%h2= t('right.column.user.header')

%address
  %strong= current_user.display_name
  %br
  = link_to current_user.email, "mailto:#{current_user.email}"

app/views/shared/_right_not_logged_in.html.haml
%h2= t('right.column.anon.user.header')

%p= t('right.column.anon.user.body')

app/views/shared/_show_links_list.html.haml
%ul.list-unstyled
  - links.each do |link|
    %li
      = link_to link.title, link.url
      - if permitted_to?(:edit, link)
        = link_to t('link.edit'), edit_link_path(link), :class => 'btn btn-default btn-xs'
      - if permitted_to?(:destroy, link)
        = link_to t('link.delete'), link, method: :delete, data: { confirm: t('link.destroy.confirm') }, :class => 'btn btn-xs btn-danger'