config/routes.rb
Rails.application.routes.draw do
  scope "/:locale" do
    resources :genres
    resources :languages
    resources :periods
    resources :composers
    resources :account
    resources :admin_users
    resources :messages
    resources :links, :except => [:show, :index]

    resources :evensongs
#    resources :evensongs do
#      collection do
#        post 'sorted'
#      end
#    end

    resources :notes do
      collection do
        get 'voices'
      end
#      collection do
#        post 'sorted'
#      end
    end

    resources :uploads do
      collection do
        get 'link'
      end
      member do
        get 'refresh'
      end
    end

    resources :dropbox do
      collection do
        get 'authorize'
      end
    end


    match 'search/:type' => 'search#index', :as => :typedsearch, via: [:get, :post]

    match 'search' => 'search#search', :as => :search, via: [:get, :post]

    match 'typeahead' => 'search#typeahead', :as => :searchahead, via: [:get]

    devise_for :users

  end

  get '/:locale' => 'notes#index'
  root :to => 'notes#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable,
         :recoverable, :trackable, :timeoutable

  has_many :user_role_relations
  has_many :roles, :through => :user_role_relations

  scope :ordered, -> { order(:name) }
  scope :preloaded, -> { includes :roles }

  validates_presence_of :username, :name, :email, :roles

  def role_symbols
    roles.map do |role|
      role.name.underscore.to_sym
    end
  end

  def display_name
    name.blank? ? username : name
  end
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
  filter_access_to :all

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.ordered.preloaded
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_url, notice: t('create.user.ok') }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_users_url, notice: t('update.user.ok') }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: t('delete.user.ok') }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :name, :email, :password, :password_confirmation, :role_ids => [])
  end
end

app/views/admin_users/_actions.html.haml
- if permitted_to? :new, :admin_users
  .well
    = link_to t('button.add'), new_admin_user_path, :class => 'btn btn-primary btn-xs'

app/views/admin_users/_form.html.haml
= render 'shared/validation_messages', :errors => user.errors

.form-group
  = f.label :username, :class => 'control-label'
  = f.text_field :username, :class => 'form-control'

.form-group
  = f.label :name, :class => 'control-label'
  = f.text_field :name, :class => 'form-control'

.form-group
  = f.label :email, :class => 'control-label'
  = f.text_field :email, :class => 'form-control'

.form-group
  = f.label :password, :class => 'control-label'
  = f.password_field :password, autocomplete: 'off', :class => 'form-control'

.form-group
  = f.label :password_confirmation, :class => 'control-label'
  = f.password_field :password_confirmation, autocomplete: 'off', :class => 'form-control'

.form-group
  = f.label :roles, :class => 'control-label'
  - Role.ordered.each do |role|
    = check_box_tag 'user[role_ids][]', role.id, user.roles.include?(role)
    = role.name
    %br

app/views/admin_users/edit.html.haml
- title @user.display_name, false

.container
  .row
    .col-md-6
      %h2= @user.display_name

      = form_for @user, :url => {:controller => 'admin_users', :action => 'update'} do |f|
        = render 'form', :user => @user, :f => f

        .well
          = f.submit t('button.update'), :class => 'btn btn-primary btn-xs'
          = link_to t('button.cancel'), url_for( :controller => 'admin_users', :action => 'index'), :class => 'btn btn-default btn-xs'

app/views/admin_users/index.html.haml
- title t('page.users.title')

= render 'actions'

%table.table.table-bordered.table-condensed.table-striped
  %thead
    %tr
      %th= t('table.title.username')
      %th= t('table.title.name')
      %th= t('table.title.email')
      %th= t('table.title.sign_in_count')
      %th= t('table.title.current_sign_in_at')
      %th= t('table.title.last_sign_in_at')
      %th= t('table.title.current_sign_in_ip')
      %th= t('table.title.last_sign_in_ip')
      %th= t('table.title.roles')
      %th
  %tbody
    - @users.each do |item|
      %tr
        %td= link_to item.username, admin_user_path(item)
        %td= item.name
        %td= item.email
        %td= item.sign_in_count
        %td= item.current_sign_in_at
        %td= item.last_sign_in_at
        %td= item.current_sign_in_ip
        %td= item.last_sign_in_ip
        %td
          %ul.list-unstyled
            - item.roles.each do |role|
              %li= role.name
        %td
          - if permitted_to? :edit, item
            = link_to t('button.edit'), edit_admin_user_path(item), :class => 'btn btn-default btn-xs'
          - if permitted_to? :destroy, item
            = link_to t('link.delete'), admin_user_path(item), method: :delete, data: { confirm: t('link.destroy.confirm') }, :class => 'btn btn-xs btn-danger'


= render 'actions'

app/views/admin_users/new.html.haml
- title t('page.user.title'), false

.container
  .row
    .col-md-6
      %h2= t('page.user.title')

      = form_for @user, :url => {:controller => 'admin_users', :action => 'create'} do |f|
        = render 'form', :user => @user, :f => f

        .well
          = f.submit t('button.update'), :class => 'btn btn-primary btn-xs'
          = link_to t('button.cancel'), url_for( :controller => 'admin_users', :action => 'index'), :class => 'btn btn-default btn-xs'

app/views/admin_users/show.html.haml
- title @user.display_name

%table.table.table-bordered.table-condensed.table-striped
  %thead
    %tr
      %th= t('table.title.username')
      %td= @user.username
    %tr
      %th= t('table.title.name')
      %td= @user.name
    %tr
      %th= t('table.title.email')
      %td= @user.email
    %tr
      %th= t('table.title.sign_in_count')
      %td= @user.sign_in_count
    %tr
      %th= t('table.title.current_sign_in_at')
      %td= @user.current_sign_in_at
    %tr
      %th= t('table.title.last_sign_in_at')
      %td= @user.last_sign_in_at
    %tr
      %th= t('table.title.current_sign_in_ip')
      %td= @user.current_sign_in_ip
    %tr
      %th= t('table.title.last_sign_in_ip')
      %td= @user.last_sign_in_ip
    %tr
      %th= t('table.title.reset_password_token')
      %td= @user.reset_password_token
    %tr
      %th= t('table.title.reset_password_sent_at')
      %td= @user.reset_password_sent_at
    %tr
      %th= t('table.title.roles')
      %td
        %ul.list-unstyled
          - @user.roles.each do |role|
            %li= role.name

.well
  - if permitted_to? :edit, @user
    = link_to t('button.edit'), edit_admin_user_path(@user), :class => 'btn btn-primary btn-xs'
  - if permitted_to? :index, :admin_users
    = link_to t('button.back'), admin_users_path, :class => 'btn btn-default btn-xs'